import type { ExampleItem, ExamplePlacement } from "@/lib/examples/types";

/**
 * Static commentary examples for Home. Add entries here to grow the catalog;
 * placement sets control which UI surface may show each item.
 */
export const EXAMPLE_ITEMS: readonly ExampleItem[] = [
  { id: "goal-001", text: "押し込んだ！", category: "goal", difficulty: "easy", placement: "chip" },
  { id: "goal-002", text: "先制ゴールだ！", category: "goal", difficulty: "easy", placement: "chip" },
  { id: "goal-003", text: "同点に追いついた！", category: "goal", difficulty: "easy", placement: "chip" },
  { id: "goal-004", text: "逆転ゴールだ！", category: "goal", difficulty: "easy", placement: "chip" },
  { id: "goal-005", text: "ヘディングで決めた！", category: "goal", difficulty: "easy", placement: "chip" },
  { id: "goal-006", text: "ボレーが決まった！", category: "goal", difficulty: "easy", placement: "chip" },
  { id: "goal-007", text: "こぼれ球を決めた！", category: "goal", difficulty: "easy", placement: "chip" },
  { id: "goal-008", text: "ニアを抜いた！", category: "goal", difficulty: "medium", placement: "chip" },
  { id: "goal-009", text: "ファーへ流し込んだ！", category: "goal", difficulty: "easy", placement: "chip" },
  { id: "goal-010", text: "終盤に決めた！", category: "goal", difficulty: "easy", placement: "chip" },
  { id: "goal-011", text: "ゴール前のこぼれ球を冷静に押し込んだ！", category: "goal", difficulty: "easy", placement: "extended" },
  { id: "goal-012", text: "ニアサイドを鋭く抜いて先制点を奪った！", category: "goal", difficulty: "easy", placement: "extended" },
  { id: "goal-013", text: "ファーへ流し込んで試合を振り出しに戻した！", category: "goal", difficulty: "easy", placement: "extended" },
  { id: "goal-014", text: "鋭いクロスに頭で合わせてネットを揺らした！", category: "goal", difficulty: "easy", placement: "extended" },
  { id: "goal-015", text: "豪快なボレーがゴール左隅に突き刺さった！", category: "goal", difficulty: "easy", placement: "extended" },
  { id: "goal-016", text: "ループシュートで飛び出したキーパーを越えた！", category: "goal", difficulty: "hard", placement: "extended" },
  { id: "goal-017", text: "終盤の勝ち越し弾でスタジアムが大きく沸いた！", category: "goal", difficulty: "easy", placement: "extended" },
  { id: "goal-018", text: "逆転ゴールで一気に試合の流れを引き寄せた！", category: "goal", difficulty: "easy", placement: "extended" },
  { id: "goal-019", text: "ダメ押しの追加点で勝利をぐっと近づけた！", category: "goal", difficulty: "easy", placement: "extended" },
  { id: "goal-020", text: "ポストに当たった跳ね返りを素早く詰めて決めた！", category: "goal", difficulty: "hard", placement: "extended" },

  { id: "shot-001", text: "強烈なシュート！", category: "shot", difficulty: "easy", placement: "chip" },
  { id: "shot-002", text: "惜しいミドルだ！", category: "shot", difficulty: "easy", placement: "chip" },
  { id: "shot-003", text: "枠を外した！", category: "shot", difficulty: "easy", placement: "chip" },
  { id: "shot-004", text: "ポスト直撃！", category: "shot", difficulty: "easy", placement: "chip" },
  { id: "shot-005", text: "決定機を逃した！", category: "shot", difficulty: "easy", placement: "chip" },
  { id: "shot-006", text: "低い弾道だ！", category: "shot", difficulty: "easy", placement: "chip" },
  { id: "shot-007", text: "ボレーを狙った！", category: "shot", difficulty: "easy", placement: "chip" },
  { id: "shot-008", text: "ループを狙う！", category: "shot", difficulty: "easy", placement: "chip" },
  { id: "shot-009", text: "ファーを狙った！", category: "shot", difficulty: "easy", placement: "chip" },
  { id: "shot-010", text: "シュートはバーの上！", category: "shot", difficulty: "easy", placement: "chip" },
  { id: "shot-011", text: "ミドルシュートがわずかにゴール右へ外れた！", category: "shot", difficulty: "easy", placement: "extended" },
  { id: "shot-012", text: "振り向きざまのボレーは惜しくもポスト直撃だ！", category: "shot", difficulty: "hard", placement: "extended" },
  { id: "shot-013", text: "強烈な一撃だったがクロスバーを越えていく！", category: "shot", difficulty: "easy", placement: "extended" },
  { id: "shot-014", text: "角度のない位置から思い切ってシュートを放った！", category: "shot", difficulty: "easy", placement: "extended" },
  { id: "shot-015", text: "ニアを狙った一発は惜しくもキーパーの横へ外れた！", category: "shot", difficulty: "hard", placement: "extended" },
  { id: "shot-016", text: "カットインからの一撃はゴール左へわずかに外れた！", category: "shot", difficulty: "medium", placement: "extended" },
  { id: "shot-017", text: "絶好機だったがシュートは正面を突いてしまった！", category: "shot", difficulty: "easy", placement: "extended" },
  { id: "shot-018", text: "こぼれ球に反応して素早く右足を振り抜いた！", category: "shot", difficulty: "easy", placement: "extended" },

  { id: "pass-001", text: "鋭いスルーパス！", category: "pass", difficulty: "easy", placement: "chip" },
  { id: "pass-002", text: "見事なラストパス！", category: "pass", difficulty: "easy", placement: "chip" },
  { id: "pass-003", text: "ワンタッチでつないだ！", category: "pass", difficulty: "easy", placement: "chip" },
  { id: "pass-004", text: "クロスが入る！", category: "pass", difficulty: "easy", placement: "chip" },
  { id: "pass-005", text: "縦パスが通った！", category: "pass", difficulty: "easy", placement: "chip" },
  { id: "pass-006", text: "折り返した！", category: "pass", difficulty: "easy", placement: "chip" },
  { id: "pass-007", text: "長いボールだ！", category: "pass", difficulty: "easy", placement: "chip" },
  { id: "pass-008", text: "逆サイドへ展開！", category: "pass", difficulty: "easy", placement: "chip" },
  { id: "pass-009", text: "ダイレクトで落とした！", category: "pass", difficulty: "easy", placement: "chip" },
  { id: "pass-010", text: "絶妙なタイミング！", category: "pass", difficulty: "easy", placement: "chip" },
  { id: "pass-011", text: "足元への短いパスだ！", category: "pass", difficulty: "easy", placement: "chip" },
  { id: "pass-012", text: "バックパスで組み立て直す！", category: "pass", difficulty: "easy", placement: "chip" },
  { id: "pass-013", text: "鋭いスルーパスが最終ラインの裏へ通った！", category: "pass", difficulty: "easy", placement: "extended" },
  { id: "pass-014", text: "深い位置からの折り返しが決定機を呼び込んだ！", category: "pass", difficulty: "easy", placement: "extended" },
  { id: "pass-015", text: "ワンタッチの連係で相手の守備を崩していく！", category: "pass", difficulty: "easy", placement: "extended" },
  { id: "pass-016", text: "逆サイドへの大きな展開で一気に局面を変えた！", category: "pass", difficulty: "medium", placement: "extended" },
  { id: "pass-017", text: "低いクロスがゴール前へ速く送り込まれた！", category: "pass", difficulty: "easy", placement: "extended" },
  { id: "pass-018", text: "縦パス一本で中央のスペースを鮮やかに突いた！", category: "pass", difficulty: "easy", placement: "extended" },
  { id: "pass-019", text: "ダイレクトパスがリズムよく前線へつながった！", category: "pass", difficulty: "easy", placement: "extended" },
  { id: "pass-020", text: "ロングパスがぴたりと収まり攻撃の起点になった！", category: "pass", difficulty: "easy", placement: "extended" },
  { id: "pass-021", text: "狭い局面でも落ち着いてワンツーを成功させた！", category: "pass", difficulty: "hard", placement: "extended" },
  { id: "pass-022", text: "ラストパスがわずかに合わず好機を逃した！", category: "pass", difficulty: "easy", placement: "extended" },

  { id: "save-001", text: "キーパーが止めた！", category: "save", difficulty: "easy", placement: "chip" },
  { id: "save-002", text: "スーパーセーブ！", category: "save", difficulty: "easy", placement: "chip" },
  { id: "save-003", text: "片手ではじいた！", category: "save", difficulty: "easy", placement: "chip" },
  { id: "save-004", text: "足で止めた！", category: "save", difficulty: "easy", placement: "chip" },
  { id: "save-005", text: "至近距離で防いだ！", category: "save", difficulty: "easy", placement: "chip" },
  { id: "save-006", text: "正面でキャッチ！", category: "save", difficulty: "easy", placement: "chip" },
  { id: "save-007", text: "飛び出して止めた！", category: "save", difficulty: "medium", placement: "chip" },
  { id: "save-008", text: "連続で防いだ！", category: "save", difficulty: "easy", placement: "chip" },
  { id: "save-009", text: "パンチングで逃れる！", category: "save", difficulty: "medium", placement: "chip" },
  { id: "save-010", text: "一対一を止めた！", category: "save", difficulty: "easy", placement: "chip" },
  { id: "save-011", text: "至近距離からの一撃を反応よくはじき出した！", category: "save", difficulty: "medium", placement: "extended" },
  { id: "save-012", text: "飛び出したキーパーが一対一を見事に制した！", category: "save", difficulty: "medium", placement: "extended" },
  { id: "save-013", text: "強烈なミドルシュートを片手一本で防いだ！", category: "save", difficulty: "hard", placement: "extended" },
  { id: "save-014", text: "こぼれ球にも素早く反応して連続セーブだ！", category: "save", difficulty: "medium", placement: "extended" },
  { id: "save-015", text: "足を伸ばしてニアサイドへの一撃を止めた！", category: "save", difficulty: "medium", placement: "extended" },
  { id: "save-016", text: "難しいバウンドにも落ち着いてキャッチした！", category: "save", difficulty: "easy", placement: "extended" },

  { id: "dribble-001", text: "一人かわした！", category: "dribble", difficulty: "easy", placement: "chip" },
  { id: "dribble-002", text: "縦へ突破する！", category: "dribble", difficulty: "easy", placement: "chip" },
  { id: "dribble-003", text: "中へ切り込む！", category: "dribble", difficulty: "easy", placement: "chip" },
  { id: "dribble-004", text: "スピードで抜いた！", category: "dribble", difficulty: "easy", placement: "chip" },
  { id: "dribble-005", text: "巧みなフェイント！", category: "dribble", difficulty: "easy", placement: "chip" },
  { id: "dribble-006", text: "ボールを失わない！", category: "dribble", difficulty: "easy", placement: "chip" },
  { id: "dribble-007", text: "タッチライン際を進む！", category: "dribble", difficulty: "medium", placement: "chip" },
  { id: "dribble-008", text: "二人をかわした！", category: "dribble", difficulty: "medium", placement: "chip" },
  { id: "dribble-009", text: "スピードに乗ったドリブルで一人をかわした！", category: "dribble", difficulty: "medium", placement: "extended" },
  { id: "dribble-010", text: "タッチライン際を巧みに運んで一気に前進した！", category: "dribble", difficulty: "medium", placement: "extended" },
  { id: "dribble-011", text: "中へ切れ込みながら守備の間をすり抜けていく！", category: "dribble", difficulty: "medium", placement: "extended" },
  { id: "dribble-012", text: "細かいタッチで複数の相手をかわしてみせた！", category: "dribble", difficulty: "hard", placement: "extended" },
  { id: "dribble-013", text: "体を上手く使ってボールをキープし続けた！", category: "dribble", difficulty: "medium", placement: "extended" },
  { id: "dribble-014", text: "鋭い切り返しで対応した守備を置き去りにした！", category: "dribble", difficulty: "hard", placement: "extended" },

  { id: "defending-001", text: "見事なブロック！", category: "defending", difficulty: "easy", placement: "chip" },
  { id: "defending-002", text: "体を張った守備だ！", category: "defending", difficulty: "easy", placement: "chip" },
  { id: "defending-003", text: "インターセプト成功！", category: "defending", difficulty: "easy", placement: "chip" },
  { id: "defending-004", text: "しっかりクリア！", category: "defending", difficulty: "easy", placement: "chip" },
  { id: "defending-005", text: "鋭いタックルだ！", category: "defending", difficulty: "easy", placement: "chip" },
  { id: "defending-006", text: "コースを切った！", category: "defending", difficulty: "easy", placement: "chip" },
  { id: "defending-007", text: "空中戦で勝った！", category: "defending", difficulty: "easy", placement: "chip" },
  { id: "defending-008", text: "プレスが効いている！", category: "defending", difficulty: "medium", placement: "chip" },
  { id: "defending-009", text: "最後は体を投げ出してシュートをブロックした！", category: "defending", difficulty: "medium", placement: "extended" },
  { id: "defending-010", text: "読みのいいインターセプトで攻撃を止めた！", category: "defending", difficulty: "medium", placement: "extended" },
  { id: "defending-011", text: "カバーリングが間に合って決定機を防いだ！", category: "defending", difficulty: "medium", placement: "extended" },
  { id: "defending-012", text: "ゴールライン上でのクリアが失点を防いだ！", category: "defending", difficulty: "hard", placement: "extended" },
  { id: "defending-013", text: "粘り強いプレスで相手に前を向かせなかった！", category: "defending", difficulty: "medium", placement: "extended" },
  { id: "defending-014", text: "鋭いタックルで足元からきれいに奪い取った！", category: "defending", difficulty: "medium", placement: "extended" },
  { id: "defending-015", text: "シュートコースを消しながら冷静に対応した！", category: "defending", difficulty: "medium", placement: "extended" },
  { id: "defending-016", text: "高いボールにも競り勝って危険をはね返した！", category: "defending", difficulty: "easy", placement: "extended" },

  { id: "set-piece-001", text: "コーナーキックだ！", category: "set-piece", difficulty: "easy", placement: "chip" },
  { id: "set-piece-002", text: "フリーキックの好機！", category: "set-piece", difficulty: "easy", placement: "chip" },
  { id: "set-piece-003", text: "PKを獲得！", category: "set-piece", difficulty: "easy", placement: "chip" },
  { id: "set-piece-004", text: "壁を越えた！", category: "set-piece", difficulty: "easy", placement: "chip" },
  { id: "set-piece-005", text: "ニアへ速いボール！", category: "set-piece", difficulty: "medium", placement: "chip" },
  { id: "set-piece-006", text: "ファーを狙う！", category: "set-piece", difficulty: "easy", placement: "chip" },
  { id: "set-piece-007", text: "セカンドボールだ！", category: "set-piece", difficulty: "easy", placement: "chip" },
  { id: "set-piece-008", text: "素早いリスタート！", category: "set-piece", difficulty: "easy", placement: "chip" },
  { id: "set-piece-009", text: "鋭いコーナーキックがニアへ送り込まれた！", category: "set-piece", difficulty: "medium", placement: "extended" },
  { id: "set-piece-010", text: "直接狙ったフリーキックは壁を越えていった！", category: "set-piece", difficulty: "medium", placement: "extended" },
  { id: "set-piece-011", text: "ファーサイドへのボールに味方が飛び込んだ！", category: "set-piece", difficulty: "medium", placement: "extended" },
  { id: "set-piece-012", text: "こぼれたセカンドボールから再びチャンスだ！", category: "set-piece", difficulty: "medium", placement: "extended" },
  { id: "set-piece-013", text: "素早いリスタートで相手の隙を突いた！", category: "set-piece", difficulty: "easy", placement: "extended" },
  { id: "set-piece-014", text: "PKの駆け引きを制して落ち着いて決め切った！", category: "set-piece", difficulty: "hard", placement: "extended" },

  { id: "general-001", text: "試合開始です！", category: "general", difficulty: "easy", placement: "chip" },
  { id: "general-002", text: "後半スタート！", category: "general", difficulty: "easy", placement: "chip" },
  { id: "general-003", text: "試合終了です！", category: "general", difficulty: "easy", placement: "chip" },
  { id: "general-004", text: "テンポが上がる！", category: "general", difficulty: "easy", placement: "chip" },
  { id: "general-005", text: "流れが変わった！", category: "general", difficulty: "easy", placement: "chip" },
  { id: "general-006", text: "カウンターの形だ！", category: "general", difficulty: "easy", placement: "chip" },
  { id: "general-007", text: "ボールを保持する！", category: "general", difficulty: "easy", placement: "chip" },
  { id: "general-008", text: "一気に前へ出る！", category: "general", difficulty: "easy", placement: "chip" },
  { id: "general-009", text: "観客が沸いている！", category: "general", difficulty: "easy", placement: "chip" },
  { id: "general-010", text: "危ない場面だ！", category: "general", difficulty: "easy", placement: "chip" },
  { id: "general-011", text: "追加時間に入ります！", category: "general", difficulty: "medium", placement: "chip" },
  { id: "general-012", text: "攻守の切り替えが速い！", category: "general", difficulty: "medium", placement: "chip" },
  { id: "general-013", text: "主導権を握っている！", category: "general", difficulty: "medium", placement: "chip" },
  { id: "general-014", text: "チャンスの匂いがする！", category: "general", difficulty: "easy", placement: "chip" },
  { id: "general-015", text: "落ち着いて回している！", category: "general", difficulty: "easy", placement: "chip" },
  { id: "general-016", text: "前半から激しい展開が続いている！", category: "general", difficulty: "medium", placement: "extended" },
  { id: "general-017", text: "後半立ち上がりからテンポの速い攻防だ！", category: "general", difficulty: "medium", placement: "extended" },
  { id: "general-018", text: "ボール保持からじっくり攻撃を組み立てている！", category: "general", difficulty: "medium", placement: "extended" },
  { id: "general-019", text: "攻守の切り替えが速く息をつかせない展開だ！", category: "general", difficulty: "medium", placement: "extended" },
  { id: "general-020", text: "カウンターの応酬で試合が大きく揺れている！", category: "general", difficulty: "hard", placement: "extended" },
  { id: "general-021", text: "この時間帯は守る側にとって苦しい流れだ！", category: "general", difficulty: "medium", placement: "extended" },
  { id: "general-022", text: "スタジアム全体が次のプレーを待ち構えている！", category: "general", difficulty: "medium", placement: "extended" },
  { id: "general-023", text: "追加時間に入り緊張感がさらに高まってきた！", category: "general", difficulty: "medium", placement: "extended" },
  { id: "general-024", text: "一つのプレーで流れが大きく変わりそうだ！", category: "general", difficulty: "medium", placement: "extended" },
  { id: "general-025", text: "前へ急ぐのか落ち着かせるのか判断が問われる！", category: "general", difficulty: "hard", placement: "extended" },
  { id: "general-026", text: "チャンスの場面で観客の期待も一気に高まる！", category: "general", difficulty: "easy", placement: "extended" },
  { id: "general-027", text: "ピンチをしのいで再び前向きな流れを作りたい！", category: "general", difficulty: "medium", placement: "extended" },
  { id: "general-028", text: "中盤での攻防が試合のリズムを左右している！", category: "general", difficulty: "medium", placement: "extended" },
  { id: "general-029", text: "このプレーが次の大きなチャンスにつながりそうだ！", category: "general", difficulty: "medium", placement: "extended" },
  { id: "general-030", text: "最後までどちらに転ぶかわからない接戦が続く！", category: "general", difficulty: "medium", placement: "extended" },

] as const;

export function getExamplesByPlacement(
  placement: ExamplePlacement
): ExampleItem[] {
  return EXAMPLE_ITEMS.filter((item) => item.placement === placement);
}
